name: Open Distro for Elasticsearch ODBC Driver

on: [push, pull_request]

jobs:    
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: run-cppcheck
      run: |
        brew install cppcheck
        sh run_cppcheck.sh
    - name: upload-cppcheck-results
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: cppcheck-results
        path: cppcheck-results.log
    - name: get-dependencies
      run: |
        brew unlink unixodbc
        brew install curl
        brew install cmake
        brew install libiodbc
    - name: aws-sdk-cpp-setup
      run: |
        sh aws_sdk_cpp_setup.sh
    - name: configure
      run: |
        prefix_path=$(pwd)
        mkdir cmake-build
        cd cmake-build
        cmake ../src -D CMAKE_INSTALL_PREFIX=$prefix_path/AWSSDK/
        cd ..
    - name: build-driver
      run: |
        cmake --build cmake-build
    #- name: test
    #  run: | 
    #    bash ./run_test_runner.sh
    - name: build-installer
      if: success()
      run: |
        cd cmake-build
        cmake ../src -D CMAKE_INSTALL_PREFIX=$prefix_path/AWSSDK/ -D BUILD_WITH_TESTS=OFF
        make
        cpack .
        cd ..
    - name: create-output
      if: success()
      run: |
        mkdir build
        mkdir test-output
        mkdir installer
        cp ./lib64/*.dylib build
        cp ./lib64/*.a build
        cp $(ls -d bin64/* | grep -v "\.") build
        cp ./cmake-build/*.pkg installer
    #    cp ./bin64/*.html test-output
    #    cp ./bin64/*.log test-output
    - name: upload-build
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: mac-build
        path: build
    - name: upload-installer
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: mac-installer
        path: installer
    #- name: upload-test-results
    #  if: success()
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: mac-test-results
    #    path: test-output
